### ISSUE TITLE
Button is not aligned

### ISSUE THREAD

**Issue by eko24ive** [vickyantre/Hw3#2]
Green button needs to be centered:
![image](https://cloud.githubusercontent.com/assets/25591824/22870326/e99abed4-f1ae-11e6-807f-52a9b46b8d8b.png)

**Comment by vickyantre** [comment]
I cann`t fix it.

**Comment by eko24ive** [comment]
Yeah, I see you have some troubles with it:
![image](https://cloud.githubusercontent.com/assets/25591824/22927741/a5712cb2-f2bb-11e6-9463-5b590355f4ac.png)

Could you tell me what you've tried to do, or maybe some specific questions to this problem ?

**Comment by vickyantre** [comment]
i tried align: center; and margin: 0 auto; and align-self

but it does not work

**Comment by vickyantre** [comment]
done

**Comment by eko24ive** [comment]
Awesome !
Thats what I wanted to see
